version: "3"
services:
  seabot:
    build: .
    restart: always
    container_name: seabot_wx
    volumes:
      - "./src/:/seabot_wx/"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
