version: "3"
services:
  seabot:
    build: .
    restart: always
    container_name: seabot_wx
    volumes:
      - "./:/seabot_wx/"
    ports:
      - "1024:8080" # 映射端口到宿主机 宿主机端口:容器端口
    environment:
      - TZ=Asia/Shanghai
