version: "3"
services:
  seabot:
    build: .
    restart: always
    container_name: seabot_ewx
    volumes:
      - "./src/:/seabot_ewx/"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
